/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTE1 (number 2), J2[20]/UART1_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTB0 (number 35), J24[2]/LLWU_P5
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE8_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE8_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE8_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC2 (number 45), J24[8]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE4b_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE4b_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE4b_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD5 (number 62), J2[12]/BLUE_LED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE6b_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE6b_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE6b_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD6 (number 63), J2[8]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE7b_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE7b_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE7b_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB1 (number 36), J24[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE9_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE9_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE9_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTB2 (number 37), J24[12]/U8[4]/ADC0_SE12/I2C0_SCL/AUD/ACCEL_I2C/POT_5K
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE12_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE12_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE12_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB3 (number 38), J24[10]/U8[6]/ADC0_SE13/I2C0_SDA/AUD/ACCEL_I2C
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE13_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE13_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE13_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC0 (number 43), J2[5]/U13[3]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE14_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE14_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE14_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC1 (number 44), J24[6]/LLWU_P6/ADC0_SE15/PUSH_BUTTON2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0SE15_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0SE15_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0SE15_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name ADC0_DP0 (number 9), J24[1]/ADC0_DP0/ADC0_SE0
  @{ */
/* @} */

/*! @name ADC0_DM0 (number 10), J24[3]/ADC0_DM0/ADC0_SE4a
  @{ */
/* @} */

/*! @name ADC0_DP3 (number 11), J24[5]/ADC0_DP3/ADC0_SE3/LIGHT_SNSR
  @{ */
/* @} */

/*! @name ADC0_SE23 (number 18), J24[11]/DAC0_OUT/ADC0_SE23
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
