/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA1 (number 23), J2[4]/RED_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LEDRGB_RED_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LEDRGB_RED_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LEDRGB_RED_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LEDRGB_RED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LEDRGB_RED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTD4 (number 61), J2[6]/SPI0_PCS1/LLWU_P14
  @{ */

/* Symbols to be used with PORT driver */
#define DSPI1_INITPINS_RF_CS_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define DSPI1_INITPINS_RF_CS_PIN 4U                   /*!<@brief PORT pin number */
#define DSPI1_INITPINS_RF_CS_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD5 (number 62), J2[12]/BLUE_LED
  @{ */

/* Symbols to be used with PORT driver */
#define DSPI1_INITPINS_LEDRGB_BLUE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define DSPI1_INITPINS_LEDRGB_BLUE_PIN 5U                   /*!<@brief PORT pin number */
#define DSPI1_INITPINS_LEDRGB_BLUE_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void DSPI1_InitPins(void);

/*! @name PORTD4 (number 61), J2[6]/SPI0_PCS1/LLWU_P14
  @{ */

/* Symbols to be used with PORT driver */
#define DSPI1_DEINITPINS_RF_CS_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define DSPI1_DEINITPINS_RF_CS_PIN 4U                   /*!<@brief PORT pin number */
#define DSPI1_DEINITPINS_RF_CS_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTD5 (number 62), J2[12]/BLUE_LED
  @{ */

/* Symbols to be used with PORT driver */
#define DSPI1_DEINITPINS_LEDRGB_BLUE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define DSPI1_DEINITPINS_LEDRGB_BLUE_PIN 5U                   /*!<@brief PORT pin number */
#define DSPI1_DEINITPINS_LEDRGB_BLUE_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void DSPI1_DeinitPins(void);

/*! @name PORTE1 (number 2), J2[20]/UART1_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define I2C1_INITPINS_DEBUG_UART_RX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define I2C1_INITPINS_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define I2C1_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C1_InitPins(void);

/*! @name PORTE1 (number 2), J2[20]/UART1_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define I2C1_DEINITPINS_DEBUG_UART_RX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define I2C1_DEINITPINS_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define I2C1_DEINITPINS_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C1_DeinitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
